image:
  file: .gitpod.Dockerfile

tasks:
  - name: install formatter
    command: python3 -m pip install autopep8 && exit

github:
  prebuilds:
    master: true

vscode:
  extensions:
    - ms-pyright.pyright
    - mtsmfm.vscode-stl-viewer
    - ms-python.python
    - roipoussiere.cadquery
