image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true

vscode:
  extensions:
    - ms-pyright.pyright
    - mtsmfm.vscode-stl-viewer
    - ms-python.python
    - ms-python.isort
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - roipoussiere.cadquery
