image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true

vscode:
  extensions:
    - ms-pyright.pyright
    - mtsmfm.vscode-stl-viewer

tasks:
  - name: 'install python packages'
    command: pip install -r requirements.txt && exit
